---
title: "Basic Probability Concepts"
author: "Manideep Bangaru"
date: "22/11/2020"
output: html_document
---
\

#### Introduction

* The priciples of probability help bridge the worlds of descriptive statistics and inferential statistics
* Probability is the numerical value representing the chance, likelihood, or possibility that a particular event will occur
* An event that has no chance of occurring has a probability of 0
* An event that is sure to occur has a probability of 1

There are three types of probability:\

* A priori\
* Empirical\
* Subjective\
\

#### Probability of Occurence

$\sf \text{Probability of Occurrence} = \large \frac{X}{T}$

$\sf \text{Where, X = number of ways in which the event occurs}$

$\sf \ \ \ \ \ \ \ \ \ \ \ \ \ \text{T = total number of possible outcomes}$

In a _**priori probability**_,the probability of an occurrence is based on priori knowledge of the process involved. For example, number of ways the event occurs and the total number of possible outcomes are known from the composition of the deck of cards or the faces of the die.

In the _**empirical probability**_ approach, the probabilities are based on observed data, not on priori knowledge process. For example, Surverys are often used to generate empirical probabilities.

_**subjective probability**_ differs from the other two approaches because, this type of probability differs from person to person, hence the name **Subjective**. This probability is usually based on individuals's past experience, personal opinion, and analysis of a particular situation. Subjective probability is especially useful in making decisions in situations in which you cannot use _**a priori**_ probability or _**empirical probability**_.
\
\

#### Experiment
It refers to an activity or measurement that results in an outcome\
_Example_: Tossing a single coin for 50 times
\
\

#### Event
Each  possible outcome of a variable is reffered to as an event
\
\

#### Equally likely Events
In a sample space containing at least two events, the chance of the occurence of each of the event is same\
_Example_: In a coss tossing experiment, having a head or tail is equal to 1/2 of each
\
\

#### Mutually Exclusive events
At a time if there is only one outcome,then the event is said to be mutually exclusive\
_Example_: Coin tossing experiment, only one outcome at a time. heads or tails
\
\

#### Outcome
Result of a random experiment is called an outcome\
_Example_: In coin tossing experiment, the two outcomes are head and tail
\
\

#### Events and Sample spaces
When you toss a coin, possible outcomes are either head or tail. Each of these are called as a simple event.
\
\

##### Joint event 
A joint event has two or more characteristics\
Getting two heads when you toss a coin twice is an example of a joint event because it consists of heads on the first toss and heads on the second toss
\
\

##### Complement
The complement of event **A** is represented by $\bf A^\prime$\
The complement of head is a tail in a coin toss as it is the only event that is not a head
\
\

##### Sample Space
The collection of all possible events is called the **sample space**\

* The sample space for tossing a coin is heads and tails\
* The sample space for rolling a die is 1,2,3,4,5,6
\
\

#### Simple Probability
It refers to the probability of occurrence of a simple event,**P(A)**\
\
$\text{Probability of Occurrence} = \frac{\large \text{Number of ways in which the event occurs}}{\large \text{Total number of events}}$\

* $0 \le P(A) \le 1$\
* $P(A) + P(A^\prime) = 1$
\
\

#### Joint Probability
Whereas simple probability refers to the probability of occurrence of simple events, joint probability refers to the probability of an occurrence involving two or more events
An example, joint probability is the probability that you will get heads on the first toss of a coin and heads on the second toss of a coin
\
\

#### Marginal Probability
The Marginal probability of an event consists of a set of joint probabilities.\
For example, if B consists of two events $\bf B_1$ and $\bf B_2$, then P(A), the probility of event A, consists of the joint probability of event A occurring with event $\bf B_1$ and event $\bf B_2$\

Marginal Probability P(A) = P(A and $B_1$) + P(A and $B_2$) + .... + P(A and $B_k$)
\
$\text{Where }B_1,B_2,....,B_k \text{ are k mutually exclusive and collectively exhaustive events}$
\
\

#### General Additional Rule
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ P(A or B) = P(A) + P(B) - P(A and B)
\
\

#### Conditional Probability
Conditional probability refers to the occurrence of event A, given information about the occurrence of another event B

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ $P(A|B) = \large \frac {P(A\cap B)}{P(B)}$\
\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ $P(B|A) = \large \frac {P(A\cap B)}{P(A)}$
\
\

#### Independence
Two events, A and B are said to be independent only if\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ P(A|B) = P(A)\
where,\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ P(A|B) = Conditional probability of A and B\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ P(A) \ \ \ = Marginal probability of A
\
\

#### General Multiplication Rule
The probability of A and B is equal to the probability of A given B times the probability of B

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ $P(A\cap B) = P(A|B) * P(B)$
\

Multiplication rule for independent events is derived by substituting P(A) for P(A|B) in the above equation\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ $P(A\cap B) = P(A) * P(B)$
\

If this rule holds for two events, A and B, then A and B are independent.\

Therefore, there are two ways to determine independence :\ 

* Events A and B are independent if, and only if, P(A|B) = P(A)\
* Events A and B are independent if, and only if, $P(A\cap B) = P(A) * P(B)$
\
\

#### Marginal probability using General Multiplication Rule
\ \ \ \ \ \ \ \ P(A) = P(A|$B_1$) * P($B_1$) + P(A|$B_2$) * P($B_2$) + ..... + P(A|$B_k$) * P($B_k$)
\
\

#### Bayesian Theorem
\ \ \ \ \ \ \ \ P($A_i$|B) = $\large \frac{P(A_i)*P(B|A_i)}{\large \sum_{\large i=1}^{\large n} P(A_i)*P(B|A_i)} \ ,\normalsize i = 1,2,3,....,n$